### ISSUE TITLE
Flash of nav menu items from 959px and below when the site is reloaded

### ISSUE THREAD

**Issue by srikat** [studiopress/genesis-sample#102]
Tested this on https://demo.studiopress.com/genesis-sample/

When the site is viewed at smaller widths (959px and below), reloading the site by either hitting the browser reload button or clicking on the site title link is showing the primary nav menu items one below the other momentarily before the hamburger menu appears.

Screencast: https://www.youtube.com/watch?v=M93ZcRpREJQ

I did not experience this on actual iPhone X.

It would be nice to get this fixed on desktops.

**Comment by nickcernis** [comment]
Thanks for this report and for taking the time to make this screencast, @srikat.

The full menu may be temporarily visible before the hamburger menu appears on some devices and network connections due to the way mobile menus are handled in https://github.com/copyblogger/responsive-menus.

The strategy applied there is to:

- Allow the full menu to load at all widths.
- Hide the menu and add the button toggle once JS is available.

The reasons for this approach are:

- To make sure that a menu appears at smaller widths even if JavaScript is disabled or fails to load. (We could hide the full menu at small widths with CSS, but if JS then fails to load for any reason it will never be visible or accessible.)
- To prevent the hamburger button from being visible at any stage during load but not clickable. (Adding it with JS ensures the element is interactive when it appears.) 

The side-effect of seeing the mobile menu that you mention here is a compromise for the above benefits. If you have ideas to fix the menu flash without losing those benefits, though, please feel free to share them — it would be a good improvement.

**Comment by lopwalj** [comment]
I think adding a `no-js` body class might do the trick so you can hide the menu by default but display it if `no-js` class is present so the menu remains visible or accessible.
https://github.com/GaryJones/genesis-js-no-js

**Comment by srikat** [comment]
I will install Gary's plugin and give it a go.

Meanwhile, want to report on something related that I noticed.

With JS blocked in Google Chrome, sub menus no longer appear when top-level menu items are hovered. I think this is a far more important issue to fix than the menu items flash.

**Comment by mjsdiaz** [comment]
At line 1082 display: block is needed
```.genesis-nav-menu .menu-item:hover > .sub-menu {
	left: auto;
	opacity: 1;
	display: block; /* added */
}```
At line 1101
```.nav-primary {
	clear: left;
	width: 100%;
	padding-top: 15px;  /* added */
}```
Line 1482
```/*.genesis-responsive-menu */.genesis-nav-menu .sub-menu,
	/*.genesis-responsive-menu*/ .genesis-nav-menu .sub-menu a {
		width: 180px;
	}```
I think that's all. (I hope the code comes out OK)

**Comment by mjsdiaz** [comment]
At Line 1082
.genesis-nav-menu .menu-item:hover > .sub-menu {
	left: auto;
	opacity: 1;
	display: block; /* added */
}
At line 1101
.nav-primary {
	clear: left;
	width: 100%;
	padding-top: 15px;  /* added */
}
Line 1482
@media only screen and (min-width: 960px) {
	/*.genesis-responsive-menu */.genesis-nav-menu .sub-menu,
	/*.genesis-responsive-menu*/ .genesis-nav-menu .sub-menu a {
		width: 180px;
	}
}

**Comment by MikeB8s** [comment]
Will there be a new SudioPress release of the Genesis-Sample theme with the changes made in Oct 2018?

**Comment by nickcernis** [comment]
@MikeB8s There will be a new release (but no schedule yet). The menu mentioned in this issue will also be refactored into Genesis itself in the future.

**Comment by MikeB8s** [comment]
Thanks for the update!



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by nickcernis** [comment]
I'm closing this menu issue for now, as we're expecting to move menu scripts into Genesis itself in the future, so any improvements to script loading would be developed there.

**Comment by geekykant** [comment]
As of 2021, Easiest fix ever! 

```css
@media only screen and (max-width: 800px) {
.genesis-nav-menu {
  display:none
  }
}
```
Change the max-width screen size in pixels at which your theme adds the responsive menu icon (i.e., “hamburger” menu).

**Comment by dhoulihan** [comment]
> As of 2021, Easiest fix ever!
> 
> ```css
> @media only screen and (max-width: 800px) {
> .genesis-nav-menu {
>   display:none;
>   }
> }
> ```
> 
> Change the max-width screen size in pixels at which your theme adds the responsive menu icon (i.e., “hamburger” menu).

For me, this causes nothing to appear when the mobile menu toggle button is clicked. Any easy fix? Site is swiftsalary.com
