### ISSUE TITLE
Use wp_get_theme for constants

### ISSUE THREAD

**Issue by seothemes** [studiopress/genesis-sample#130]
Instead of hardcoding the constants into each theme/version, we can just use `wp_get_theme` to pull the data from the stylesheet:

```php
$genesis_sample_theme = wp_get_theme();

// Define theme constants (do not remove).
define( 'CHILD_THEME_NAME', $genesis_sample_theme->get( 'Name' ) );
define( 'CHILD_THEME_URL', $genesis_sample_theme->get( 'ThemeURI' ) );
define( 'CHILD_THEME_VERSION', $genesis_sample_theme->get( 'Version' ) );
define( 'CHILD_THEME_HANDLE', $genesis_sample_theme->get( 'TextDomain' ) );
define( 'CHILD_THEME_DIR', get_stylesheet_directory() );
define( 'CHILD_THEME_URI', get_stylesheet_directory_uri() );
```

**Comment by nickcernis** [comment]
I agree with this, but wonder if it should happen in Genesis instead of in child themes. (i.e. if no constants are set in the Child Theme, Genesis automatically uses the stylesheet header info as the fallback and sets up those constants automatically.)

That way no constant definitions should be needed in child themes and the stylesheet header info would be enough.

**Comment by nickcernis** [comment]
Closing as @seothemes kindly moved this to the Genesis repo: https://github.com/studiopress/genesis-sample/issues/130.

Thanks for filling that, @seothemes, and for the great suggestion. :-)

**Comment by seothemes** [comment]
No probs @nickcernis, good call to put it in Genesis instead.
