### ISSUE TITLE
Add body class if content contains blocks

### ISSUE THREAD

**Issue by nickcernis** [studiopress/genesis-sample#148]
For https://github.com/studiopress/genesis-sample/issues/146, we're going to need to apply styles to static homepages that have blocks (to remove site-inner padding, for example), without affecting static homepages that use the Classic editor.

I suggest a `has-blocks` body class, added via this function or similar:

```php
add_filter( 'body_class', 'genesis_sample_has_blocks_body_class' );
function genesis_sample_has_blocks_body_class( $classes ) {
	if ( has_blocks() ) {
		$classes[] = 'has-blocks';
	}

	return $classes;
}
```

It might also be worth adding a body class that reveals the first block on the page (`first-block-[block-slug]`) so that margins/padding could be adjusted (and titles hidden, potentially) only for pages that start with a Cover Image or Atomic Blocks Call To Action block, for example. This could potentially be achieved with the existing `parse_blocks()` function or upcoming [`get_blocks()`](https://github.com/WordPress/gutenberg/pull/9208) one.

**Comment by mindctrl** [comment]
I saw a few conversations around this idea in the Gutenberg repo. Seems like the core team decided to not add a body class, since in the very near future nearly all sites would be built with blocks as the default and having the class seemed redundant. I saw a suggestion by someone to do the opposite... which is to build the default styles as if blocks exist and add a class if there are no blocks. Have any thoughts about that?

**Comment by nickcernis** [comment]
> I saw a suggestion by someone to do the opposite... which is to build the default styles as if blocks exist and add a class if there are no blocks.

That makes a lot of sense and seems more forward-thinking. Thanks for the suggestion, @mindctrl!
