### ISSUE TITLE
Skip links on homepage

### ISSUE THREAD

**Issue by dreamwhisper** [studiopress/genesis-sample#170]
Skip links are currently removed from the homepage template. However, the typical elements such as the primary navigation are present on the page.

**Comment by nickcernis** [comment]
I would like to revisit using the “Blocks” template to see if it's necessary, since using it presents a range of other issues (https://github.com/studiopress/genesis-sample/issues/164, https://github.com/studiopress/genesis-sample/issues/163).

We added some block-specific body classes in https://github.com/studiopress/genesis-sample/pull/149.

We could potentially use these in place of the homepage template to:

- Remove the page title (with CSS) if a Cover or Atomic CTA block is used first.
- Adjust padding accordingly.

Side-effects are that this would reinstate the footer widgets (also removed by the Blocks template), but that's probably not a big issue.

**Comment by dreamwhisper** [comment]
I simplified the Blocks template to eliminate some of the issues and retain the widest option for usage.

I opted not to go with front-page.php so it didn't impact the homepage if other templates or options were used.

**Comment by nickcernis** [comment]
This looks good — thanks, @dreamwhisper.

I confirmed the skip links are reinstated and the new template from https://github.com/studiopress/genesis-sample/pull/176 is good to use on other pages too.
