### ISSUE TITLE
No Parent selection for Page Attributes when using block editor

### ISSUE THREAD

**Issue by waybis** [studiopress/genesis-sample#171]
I've noticed after updating to 2.7.1 that the Parent selection is missing from the Page Attributes when using the block editor.  

2.6.0 shows the Parent selection, but not tested 2.7.0

**Comment by nickcernis** [comment]
Thanks for the report @waybis. I could not reproduce this so far with Genesis Sample 2.7.1 and Genesis 2.7.3:

<img width="1017" alt="edit_page_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/50561870-3a949f80-0d0f-11e9-818f-6c1208ccd5ef.png">

<img width="378" alt="edit_page_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/50561878-5009c980-0d0f-11e9-9712-d394243d00a1.png">

A few things you can try:

- Disable all other plugins.
- Remove any theme modifications.
- Check that other pages exist.
- Check that you're editing a page rather than a post (or a custom post type of type page rather than post).
- Check for errors in the JavaScript console.

If you track this down to Genesis 2.7.1 and can offer further steps to reproduce, please feel free to share them!

**Comment by waybis** [comment]
Thanks for giving it a try Nick. As per one of your suggestions, it was a site specific custom plugin which some pages use with url parameters, but no url parameters are defined if you view the page directly, so it throws up a js error, which causes the parent selector to break when using the block editor.  

Related issue here:
https://github.com/WordPress/gutenberg/issues/12930

So this maybe resolved later by Gutenberg or I will eliminate the js error from the plugin, either way genesis-sample is not the culprit.  

Apologies for the inconvenience and thanks again for the help.

**Comment by nickcernis** [comment]
Glad you tracked it down, @waybis! Thanks for linking to the issue and following up to let us know.
