### ISSUE TITLE
Custom Logo Support and wp-custom-logo class

### ISSUE THREAD

**Issue by rockingaryan** [studiopress/genesis-sample#308]
Hello,

I was testing the Genesis Sample and tried to remove the custom logo support but I am not able to understand the case here.

I know I can remove the 'genesis-custom-logo' support from _genesis-sample/config/theme-supports.php_ but why it does not remove the body class **wp-custom-logo** if the feature is not active and outputs the inline CSS which hides the title area?

I tried to find the function but not able to understand where it is added. In Genesis or Sample.

There is two custom logo support from 1. WordPress and 2. Genesis

`add_theme_support('custom-logo'); `
`add_theme_support('genesis-custom-logo');`

I understand that some child theme might not add the WordPress way and then it enables the Genesis Way to upload the Logo but why it does not remove the feature just by using 

```
add_action( 'after_setup_theme', 'remove_genesis_output_custom_logo', 11 );

function remove_genesis_output_custom_logo() {

    remove_theme_support('custom-logo');
    remove_theme_support('genesis-custom-logo');
}
```

We need to add this to remove it

```
add_action( 'after_setup_theme', 'remove_genesis_output_custom_logo', 11 );

function remove_genesis_output_custom_logo() {
   remove_action( 'genesis_site_title', 'the_custom_logo', 0 );
}
```

so we can reposition it later but it still outputs the **wp-custom-logo** class in the body make it really difficult to reposition and customize the default value.

**Comment by nickcernis** [comment]
Thanks for this report, @rockingaryan.

WordPress adds the `wp-custom-logo` logo class if a site has set a custom logo, even if the theme does not support `custom-logo` or `genesis-custom-logo`.

So if you set the logo, then remove `custom-logo` or `genesis-custom-logo` support, the `wp-custom-logo` body class still appears because the theme still has a custom logo set.

https://github.com/WordPress/WordPress/blob/e26f739e531b434ebba4f45525bdc3cb0650a71c/wp-includes/post-template.php#L776-L778

https://github.com/WordPress/WordPress/blob/4d1761c881a03c52e21e3efa1f7392110df61bdf/wp-includes/general-template.php#L923-L938

This is the same in Twenty Nineteen. I can:

1. Set a custom logo in the Site Identity section.
2. Remove `custom-logo` support from Twenty Nineteen in `functions.php`.
3. Twenty Nineteen continues to show the `wp-custom-logo` class (and logo) even though I can no longer change it from the Site Identity area.

The solution for Genesis Sample is to **remove the logo in the Customizer before you remove `genesis-custom-logo` support from `genesis-sample/config/theme-supports.php`**. (Or add the support back, remove the logo, then remove the support.)

You could also filter the body classes to remove `wp-custom-logo` if it has been set before theme support was removed if you wish:

```php
add_filter( 'body_class', 'genesis_sample_maybe_remove_logo_body_class' );
/**
 * Remove the `wp-custom-logo` class if a logo was set and custom-logo
 * support was then removed from the theme.
 *
 * @param array $classes Original body classes.
 * @return array New classes.
 */
function genesis_sample_maybe_remove_logo_body_class( $classes ) {
	if (
		! get_theme_support( 'genesis-custom-logo' )
		&& ! get_theme_support( 'custom-logo' )
	) {
		$custom_logo_class = array_search( 'wp-custom-logo', $classes );
		if ( $custom_logo_class ) {
			unset( $classes[ $custom_logo_class ] );
		}
	}

	return $classes;
}
```

But you don't need to do this, in my opinion. It would only be useful if you expect people to remove custom logo support for the active theme after setting a logo for the active theme. If that becomes a common occurrence, it may make sense to fix the `wp-custom-logo` body class logic in WordPress instead of Genesis.

**Comment by rockingaryan** [comment]
Hi,

Thank you for giving your time on checking this for me. `wp-custom-logo` class was not a problem and I thought it may be default from the theme.

I think it would be better just to remove the support and remove the CSS which hides the title area with conditional css which is in genesis-sample/style.css and genesis-sample/lib/output.php

Thank you!
