### ISSUE TITLE
Add starter content support

### ISSUE THREAD

**Issue by seothemes** [studiopress/genesis-sample#64]
Improves user experience, especially when importing WooCommerce demo data as images are not imported with xml files. [Example](https://github.com/woocommerce/storefront/blob/master/inc/nux/class-storefront-nux-starter-content.php)

**Comment by nickcernis** [comment]
Bumping this one to the Genesis Sample 2.8 milestone, as we're awaiting support for starter content in Genesis 2.8+.

**Comment by dreamwhisper** [comment]
Moving this out of the 2.8 milestone. We're adding homepage onboarding but full site onboarding will come in the future.

Also, I wanted to note that we provide customers a separate product XML to import WooCommerce demo data in our [setup instructions](https://my.studiopress.com/documentation/woocommerce/woocommerce-integration/how-to-import-the-demo-products/). We don't include it by default since not everyone intends to set up an ecommerce site.

**Comment by dreamwhisper** [comment]
Closing in favor of One-click Theme Setup content.
